name: Build 

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Grant execute permission
      run: | 
        chmod +x pug
        chmod -R +x scripts/
        
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Patch PugEngine
      run: |
        git config --global user.email "cunt@github.com"
        git config --global user.name "cunt"
        git submodule update --init --recursive
        ./pug jar
